version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: SupportService_Database
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data